"""added cat2

Revision ID: 100c26782296
Revises: 0f0d6b2fc203
Create Date: 2024-09-21 21:01:08.925023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100c26782296'
down_revision: Union[str, None] = '0f0d6b2fc203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('category2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'category2')
    # ### end Alembic commands ###
