"""deleted cat2

Revision ID: 7c09fa5c7969
Revises: 4c737bbe9aac
Create Date: 2024-09-21 21:02:35.203955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c09fa5c7969'
down_revision: Union[str, None] = '4c737bbe9aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'category2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('category2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
