"""initial db setup

Revision ID: 83129c92da12
Revises: e8ff86fddfba
Create Date: 2024-09-21 21:05:32.474925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83129c92da12'
down_revision: Union[str, None] = 'e8ff86fddfba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
