"""added cat2

Revision ID: fece4107e809
Revises: 7c09fa5c7969
Create Date: 2024-09-21 21:02:57.197674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fece4107e809'
down_revision: Union[str, None] = '7c09fa5c7969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('category2', sa.String(), server_default='Carrier Comparison', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'category2')
    # ### end Alembic commands ###
