"""db init

Revision ID: f0cb41e78ad3
Revises: 350b5a04adab
Create Date: 2024-09-19 23:06:14.454825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cb41e78ad3'
down_revision: Union[str, None] = '350b5a04adab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Posts_id', table_name='Posts')
    op.drop_table('Posts')
    op.drop_index('ix_Comments_id', table_name='Comments')
    op.drop_table('Comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('upvotes', sa.INTEGER(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('post_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Comments_id', 'Comments', ['id'], unique=False)
    op.create_table('Posts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('upvotes', sa.INTEGER(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('category2', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Posts_id', 'Posts', ['id'], unique=False)
    # ### end Alembic commands ###
